# Scaffolding generated by Casein v5.0.1.0

module Casein
  class AboutsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Abouts'
  		@abouts = About.order(sort_order(:about_us)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View about'
      @about = About.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new about'
    	@about = About.new
    end

    def create
      @about = About.new about_params
    
      if @about.save
        flash[:notice] = 'About created'
        redirect_to casein_abouts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new about'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update about'
      
      @about = About.find params[:id]
    
      if @about.update_attributes about_params
        flash[:notice] = 'About has been updated'
        redirect_to casein_abouts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this about'
        render :action => :show
      end
    end
 
    def destroy
      @about = About.find params[:id]

      @about.destroy
      flash[:notice] = 'About has been deleted'
      redirect_to casein_abouts_path
    end
  
    private
      
      def about_params
        params.require(:about).permit(:about_us)
      end

  end
end